site_name: Etl join excel files
theme:
  name: material
  palette:
    primary: deep blue
  language: pt

repo_name: ""
repo_url: ""

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

plugins:
  - search
  - mkdocstrings:
      default_handler: python
